"""
agents/reviewer_agent.py — Joyn Reviewer Agent

Evaluates a builder's submission package against The Bar's five gates.
This is Joyn internal infrastructure — not a product for hire.

The Bar's five gates (from JOYN-DEPLOYMENT-STANDARD.md):
  01 · Role Clarity
  02 · Output Standard
  03 · Hirer Experience
  04 · Failure Handling
  05 · Calibration Architecture

Architecture: Multi-pass LLM evaluation — one pass per gate, then
a synthesis pass for the overall verdict. Uses the Visionary Spec
as the reference document.

Triggered by: /api/builder/preflight (POST) when builder submits
their full submission package.

Returns:
  - overall_verdict: pass | conditional_pass | resubmit
  - gate_results: list of {gate, status, evidence, remediation}
  - summary: human-readable summary for the builder
  - next_steps: specific actions required
"""
from __future__ import annotations
import json
import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

try:
    from openai import OpenAI
    _client = OpenAI()
    _MODEL = os.environ.get("REVIEWER_MODEL", "gpt-4.1-mini")
    _LLM_AVAILABLE = True
except ImportError:
    _LLM_AVAILABLE = False
    logger.warning("openai package not available — ReviewerAgent running in rule-based mode")


GATE_PROMPTS = {
    "01": {
        "name": "Role Clarity",
        "description": "The staff's role must be expressible in one sentence with no jargon. A stranger should understand exactly what this staff does and who hires it.",
        "pass_criteria": "One sentence. Specific. No jargon. Unambiguous. Includes what it does AND who hires it.",
        "fail_examples": ["'AI assistant' — too vague", "'Helps with insurance stuff' — no specificity", "'Automates workflows' — meaningless"]
    },
    "02": {
        "name": "Output Standard",
        "description": "Every output must be named, formatted, triggered, and have a defined frequency. No unnamed or vague outputs.",
        "pass_criteria": "Every output has: name, format (Email/PDF/Slack/etc), trigger (what causes it), frequency (how often), recipient.",
        "fail_examples": ["'Sends reports' — not named or triggered", "'Provides analysis' — no format specified"]
    },
    "03": {
        "name": "Hirer Experience",
        "description": "The hirer's experience must be fully mapped. Total time commitment must be under 3 hours for a full engagement lifecycle. Intervention points must be explicit.",
        "pass_criteria": "Total hirer time stated. At least 2 intervention points defined. Onboarding steps clear. No surprise touchpoints.",
        "fail_examples": ["No time estimate provided", "Hirer touchpoints vague or undefined"]
    },
    "04": {
        "name": "Failure Handling",
        "description": "Three failure scenarios must be defined with specific responses. The staff must handle failures gracefully — not crash or go silent.",
        "pass_criteria": "Three distinct failure scenarios. Each has: trigger, response, hirer notification. Responses are specific, not generic.",
        "fail_examples": ["'Handles errors gracefully' — not specific", "Only one failure scenario defined"]
    },
    "05": {
        "name": "Calibration Architecture",
        "description": "The staff must have a mechanism to learn from hirer feedback and carry it forward. The calibration corpus must be structured.",
        "pass_criteria": "Feedback mechanism defined. Corpus structure described. Carry-forward logic specified. At least 3 calibration questions.",
        "fail_examples": ["'Learns from feedback' — no mechanism specified", "Fewer than 3 calibration questions"]
    }
}


def run(submission: dict, visionary_spec: Optional[dict] = None) -> dict:
    """
    Evaluate a submission package against The Bar's five gates.
    
    Parameters
    ----------
    submission : dict
        Builder's submission package (from /api/builder/preflight)
    visionary_spec : dict, optional
        The Visionary Spec generated by the Architect Agent
    
    Returns
    -------
    dict
        Full verdict with gate-by-gate results
    """
    if _LLM_AVAILABLE:
        return _llm_review(submission, visionary_spec)
    else:
        return _rule_based_review(submission, visionary_spec)


def _llm_review(submission: dict, visionary_spec: Optional[dict]) -> dict:
    """Use LLM to evaluate each gate independently."""
    gate_results = []
    
    spec_context = ""
    if visionary_spec:
        spec_context = f"\n\nVisionary Spec (the builder's approved blueprint):\n{json.dumps(visionary_spec, indent=2)}"
    
    for gate_id, gate_info in GATE_PROMPTS.items():
        gate_result = _evaluate_gate(gate_id, gate_info, submission, spec_context)
        gate_results.append(gate_result)
    
    # Determine overall verdict
    fail_count = len([g for g in gate_results if g['status'] == 'fail'])
    conditional_count = len([g for g in gate_results if g['status'] == 'conditional'])
    
    if fail_count >= 3:
        overall = 'resubmit'
    elif fail_count > 0 or conditional_count > 0:
        overall = 'conditional_pass'
    else:
        overall = 'pass'
    
    # Generate summary
    summary = _generate_summary(overall, gate_results, submission)
    
    return {
        "overall_verdict": overall,
        "gate_results": gate_results,
        "summary": summary,
        "next_steps": _get_next_steps(overall, gate_results),
        "agent": "reviewer",
        "model": _MODEL,
        "gates_passed": len([g for g in gate_results if g['status'] == 'pass']),
        "gates_failed": fail_count,
        "gates_conditional": conditional_count,
    }


def _evaluate_gate(gate_id: str, gate_info: dict, submission: dict, spec_context: str) -> dict:
    """Evaluate a single gate."""
    
    system = f"""You are the Joyn Reviewer Agent evaluating Gate {gate_id}: {gate_info['name']}.

Gate description: {gate_info['description']}
Pass criteria: {gate_info['pass_criteria']}
Common fail examples: {'; '.join(gate_info['fail_examples'])}

Evaluate ONLY this gate. Be specific. Cite evidence from the submission.
Return ONLY valid JSON:
{{
  "gate": "{gate_id}",
  "name": "{gate_info['name']}",
  "status": "<pass|conditional|fail>",
  "evidence": "<specific quote or reference from the submission that supports your verdict>",
  "remediation": "<specific action required — null if pass>"
}}

Status definitions:
- pass: Gate fully satisfied
- conditional: Gate mostly satisfied but has a specific gap that must be addressed
- fail: Gate not satisfied — significant work required"""

    prompt = f"""Submission package:{spec_context}

Builder's submission data:
{json.dumps(submission, indent=2)}

Evaluate Gate {gate_id}: {gate_info['name']}"""

    try:
        response = _client.chat.completions.create(
            model=_MODEL,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1,
            max_tokens=400,
            response_format={"type": "json_object"}
        )
        result = json.loads(response.choices[0].message.content)
        return {
            "gate": gate_id,
            "name": gate_info['name'],
            "status": result.get("status", "fail"),
            "evidence": result.get("evidence", ""),
            "remediation": result.get("remediation"),
        }
    except Exception as e:
        logger.error(f"ReviewerAgent gate {gate_id} error: {e}")
        return {
            "gate": gate_id,
            "name": gate_info['name'],
            "status": "fail",
            "evidence": f"Evaluation error: {str(e)}",
            "remediation": "Please resubmit — evaluation error occurred"
        }


def _generate_summary(overall: str, gate_results: list, submission: dict) -> str:
    """Generate a human-readable summary for the builder."""
    passed = [g for g in gate_results if g['status'] == 'pass']
    failed = [g for g in gate_results if g['status'] == 'fail']
    conditional = [g for g in gate_results if g['status'] == 'conditional']
    
    if overall == 'pass':
        return f"All five gates passed. Your submission is ready for deployment. {len(passed)} of 5 gates cleared."
    elif overall == 'conditional_pass':
        issues = conditional + failed
        gate_names = ', '.join([g['name'] for g in issues])
        return f"{len(passed)} of 5 gates passed. Specific remediation required for: {gate_names}. Address these items and resubmit those gates only."
    else:
        gate_names = ', '.join([g['name'] for g in failed])
        return f"{len(failed)} gates failed: {gate_names}. Full resubmission required. Detailed feedback provided per gate below."


def _get_next_steps(overall: str, gate_results: list) -> list:
    """Get specific next steps for the builder."""
    if overall == 'pass':
        return ["Your AI staff will be deployed to the marketplace within 48 hours.", "You will receive an email with your live listing URL."]
    
    steps = []
    for gate in gate_results:
        if gate['status'] in ('fail', 'conditional') and gate.get('remediation'):
            steps.append(f"Gate {gate['gate']} ({gate['name']}): {gate['remediation']}")
    
    if overall == 'conditional_pass':
        steps.append("Resubmit only the flagged gates — not the full submission.")
    else:
        steps.append("Address all failed gates and resubmit the complete package.")
    
    return steps


def _rule_based_review(submission: dict, visionary_spec: Optional[dict]) -> dict:
    """Fallback rule-based review when LLM is unavailable."""
    gate_results = []
    
    # Gate 01: Role Clarity
    role_def = submission.get('role_definition', '')
    if len(role_def) > 20 and len(role_def.split()) <= 30:
        gate_results.append({"gate": "01", "name": "Role Clarity", "status": "pass", "evidence": role_def[:100], "remediation": None})
    else:
        gate_results.append({"gate": "01", "name": "Role Clarity", "status": "fail", 
                              "evidence": f"Role definition is {'too long' if len(role_def.split()) > 30 else 'too vague or missing'}",
                              "remediation": "Write a single sentence (under 30 words) that describes exactly what this staff does and who hires it."})
    
    # Gate 02: Output Standard
    outputs = submission.get('named_outputs', [])
    if isinstance(outputs, list) and len(outputs) >= 1:
        complete = all(o.get('name') and o.get('format') and o.get('trigger') for o in outputs)
        if complete:
            gate_results.append({"gate": "02", "name": "Output Standard", "status": "pass", "evidence": f"{len(outputs)} named outputs defined", "remediation": None})
        else:
            gate_results.append({"gate": "02", "name": "Output Standard", "status": "conditional",
                                  "evidence": "Some outputs missing format or trigger",
                                  "remediation": "Ensure every output has: name, format, trigger, and frequency."})
    else:
        gate_results.append({"gate": "02", "name": "Output Standard", "status": "fail",
                              "evidence": "No named outputs defined",
                              "remediation": "Define at least one named output with format, trigger, and frequency."})
    
    # Gate 03: Hirer Experience
    hirer_exp = submission.get('hirer_experience', {})
    if hirer_exp and hirer_exp.get('total_time_minutes') and hirer_exp.get('intervention_points'):
        gate_results.append({"gate": "03", "name": "Hirer Experience", "status": "pass",
                              "evidence": f"Total time: {hirer_exp['total_time_minutes']} mins, {len(hirer_exp['intervention_points'])} intervention points",
                              "remediation": None})
    else:
        gate_results.append({"gate": "03", "name": "Hirer Experience", "status": "fail",
                              "evidence": "Hirer experience not fully defined",
                              "remediation": "Define total hirer time commitment and at least 2 intervention points."})
    
    # Gate 04: Failure Handling
    failures = submission.get('failure_scenarios', [])
    if isinstance(failures, list) and len(failures) >= 3:
        gate_results.append({"gate": "04", "name": "Failure Handling", "status": "pass",
                              "evidence": f"{len(failures)} failure scenarios defined", "remediation": None})
    else:
        gate_results.append({"gate": "04", "name": "Failure Handling", "status": "fail",
                              "evidence": f"Only {len(failures) if isinstance(failures, list) else 0} failure scenarios defined",
                              "remediation": "Define at least 3 failure scenarios with specific responses and hirer notifications."})
    
    # Gate 05: Calibration
    calib = submission.get('calibration_questions', [])
    if isinstance(calib, list) and len(calib) >= 3:
        gate_results.append({"gate": "05", "name": "Calibration Architecture", "status": "pass",
                              "evidence": f"{len(calib)} calibration questions defined", "remediation": None})
    else:
        gate_results.append({"gate": "05", "name": "Calibration Architecture", "status": "fail",
                              "evidence": f"Only {len(calib) if isinstance(calib, list) else 0} calibration questions",
                              "remediation": "Define at least 3 calibration questions and describe the corpus structure."})
    
    fail_count = len([g for g in gate_results if g['status'] == 'fail'])
    conditional_count = len([g for g in gate_results if g['status'] == 'conditional'])
    
    if fail_count >= 3:
        overall = 'resubmit'
    elif fail_count > 0 or conditional_count > 0:
        overall = 'conditional_pass'
    else:
        overall = 'pass'
    
    return {
        "overall_verdict": overall,
        "gate_results": gate_results,
        "summary": _generate_summary(overall, gate_results, submission),
        "next_steps": _get_next_steps(overall, gate_results),
        "agent": "reviewer",
        "model": "rule-based",
        "gates_passed": len([g for g in gate_results if g['status'] == 'pass']),
        "gates_failed": fail_count,
        "gates_conditional": conditional_count,
    }
