# prompts/__init__.py
from .sage_v1 import (
    SAGE_PERSONA,
    SAGE_SYSTEM_PROMPT,
    SAGE_OPENER,
    SAGE_GATE_PROMPTS,
    SAGE_FALLBACK_REVERSE_ENGINEER,
    SAGE_FALLBACK_QUICK_CHOICES,
    SAGE_COMPLETION_SUMMARY
)

__all__ = [
    'SAGE_PERSONA',
    'SAGE_SYSTEM_PROMPT',
    'SAGE_OPENER',
    'SAGE_GATE_PROMPTS',
    'SAGE_FALLBACK_REVERSE_ENGINEER',
    'SAGE_FALLBACK_QUICK_CHOICES',
    'SAGE_COMPLETION_SUMMARY'
]
